// @ts-check

/**
 * @typedef {Object} Province
 * @property {number} id - Province ID
 * @property {string} name - Thai name
 * @property {string} abbreviation - Abbreviation in Thai
 * @property {string} englishName - English name
 */

/** @type {Province[]} */
export const provinces = [
  {
    id: 10,
    name: "กรุงเทพมหานคร",
    abbreviation: "กทม.",
    englishName: "Bangkok",
  },
  { id: 81, name: "กระบี่", abbreviation: "กบ.", englishName: "Krabi" },
  {
    id: 71,
    name: "กาญจนบุรี",
    abbreviation: "กจ.",
    englishName: "Kanchanaburi",
  },
  { id: 46, name: "กาฬสินธุ์", abbreviation: "กส.", englishName: "Kalasin" },
  {
    id: 62,
    name: "กำแพงเพชร",
    abbreviation: "กพ.",
    englishName: "Kamphaeng Phet",
  },
  { id: 40, name: "ขอนแก่น", abbreviation: "ขก.", englishName: "Khon Kaen" },
  { id: 22, name: "จันทบุรี", abbreviation: "จบ.", englishName: "Chanthaburi" },
  {
    id: 24,
    name: "ฉะเชิงเทรา",
    abbreviation: "ฉช.",
    englishName: "Chachoengsao",
  },
  { id: 18, name: "ชัยนาท", abbreviation: "ชน.", englishName: "Chai Nat" },
  { id: 36, name: "ชัยภูมิ", abbreviation: "ชย.", englishName: "Chaiyaphum" },
  { id: 86, name: "ชุมพร", abbreviation: "ชพ.", englishName: "Chumphon" },
  { id: 20, name: "ชลบุรี", abbreviation: "ชบ.", englishName: "Chonburi" },
  { id: 57, name: "เชียงราย", abbreviation: "ชร.", englishName: "Chiang Rai" },
  { id: 50, name: "เชียงใหม่", abbreviation: "ชม.", englishName: "Chiang Mai" },
  { id: 92, name: "ตรัง", abbreviation: "ตง.", englishName: "Trang" },
  { id: 23, name: "ตราด", abbreviation: "ตร.", englishName: "Trat" },
  { id: 63, name: "ตาก", abbreviation: "ตก.", englishName: "Tak" },
  { id: 26, name: "นครนายก", abbreviation: "นย.", englishName: "Nakhon Nayok" },
  { id: 73, name: "นครปฐม", abbreviation: "นฐ.", englishName: "Nakhon Pathom" },
  { id: 48, name: "นครพนม", abbreviation: "นพ.", englishName: "Nakhon Phanom" },
  {
    id: 30,
    name: "นครราชสีมา",
    abbreviation: "นม.",
    englishName: "Nakhon Ratchasima",
  },
  {
    id: 80,
    name: "นครศรีธรรมราช",
    abbreviation: "นศ.",
    englishName: "Nakhon Si Thammarat",
  },
  {
    id: 60,
    name: "นครสวรรค์",
    abbreviation: "นว.",
    englishName: "Nakhon Sawan",
  },
  { id: 12, name: "นนทบุรี", abbreviation: "นบ.", englishName: "Nonthaburi" },
  { id: 96, name: "นราธิวาส", abbreviation: "นธ.", englishName: "Narathiwat" },
  { id: 55, name: "น่าน", abbreviation: "น่าน", englishName: "Nan" },
  { id: 97, name: "บึงกาฬ", abbreviation: "บก.", englishName: "Bueng Kan" },
  { id: 31, name: "บุรีรัมย์", abbreviation: "บร.", englishName: "Buri Ram" },
  {
    id: 13,
    name: "ปทุมธานี",
    abbreviation: "ปท.",
    englishName: "Pathum Thani",
  },
  {
    id: 77,
    name: "ประจวบคีรีขันธ์",
    abbreviation: "ปข.",
    englishName: "Prachuap Khiri Khan",
  },
  {
    id: 25,
    name: "ปราจีนบุรี",
    abbreviation: "ปร.",
    englishName: "Prachin Buri",
  },
  { id: 94, name: "ปัตตานี", abbreviation: "ปน.", englishName: "Pattani" },
  {
    id: 14,
    name: "พระนครศรีอยุธยา",
    abbreviation: "อย.",
    englishName: "Phra Nakhon Si Ayutthaya",
  },
  { id: 82, name: "พังงา", abbreviation: "พง.", englishName: "Phangnga" },
  { id: 93, name: "พัทลุง", abbreviation: "พล.", englishName: "Phatthalung" },
  { id: 66, name: "พิจิตร", abbreviation: "พจ.", englishName: "Phichit" },
  { id: 65, name: "พิษณุโลก", abbreviation: "พล.", englishName: "Phitsanulok" },
  { id: 76, name: "เพชรบุรี", abbreviation: "พบ.", englishName: "Phetchaburi" },
  { id: 67, name: "เพชรบูรณ์", abbreviation: "พช.", englishName: "Phetchabun" },
  { id: 54, name: "แพร่", abbreviation: "พร.", englishName: "Phrae" },
  { id: 56, name: "พะเยา", abbreviation: "พย.", englishName: "Phayao" },
  { id: 83, name: "ภูเก็ต", abbreviation: "ภก.", englishName: "Phuket" },
  {
    id: 44,
    name: "มหาสารคาม",
    abbreviation: "มค.",
    englishName: "Maha Sarakham",
  },
  { id: 49, name: "มุกดาหาร", abbreviation: "มด.", englishName: "Mukdahan" },
  {
    id: 58,
    name: "แม่ฮ่องสอน",
    abbreviation: "มส.",
    englishName: "Mae Hong Son",
  },
  { id: 35, name: "ยโสธร", abbreviation: "ยส.", englishName: "Yasothon" },
  { id: 95, name: "ยะลา", abbreviation: "ยล.", englishName: "Yala" },
  { id: 45, name: "ร้อยเอ็ด", abbreviation: "รอ.", englishName: "Roi Et" },
  { id: 85, name: "ระนอง", abbreviation: "รน.", englishName: "Ranong" },
  { id: 21, name: "ระยอง", abbreviation: "รย.", englishName: "Rayong" },
  { id: 70, name: "ราชบุรี", abbreviation: "รบ.", englishName: "Ratchaburi" },
  { id: 16, name: "ลพบุรี", abbreviation: "ลบ.", englishName: "Lopburi" },
  { id: 52, name: "ลำปาง", abbreviation: "ลป.", englishName: "Lampang" },
  { id: 51, name: "ลำพูน", abbreviation: "ลพ.", englishName: "Lamphun" },
  { id: 42, name: "เลย", abbreviation: "ลย.", englishName: "Loei" },
  { id: 33, name: "ศรีสะเกษ", abbreviation: "ศก.", englishName: "Si Sa Ket" },
  { id: 47, name: "สกลนคร", abbreviation: "สน.", englishName: "Sakon Nakhon" },
  { id: 90, name: "สงขลา", abbreviation: "สข.", englishName: "Songkhla" },
  { id: 91, name: "สตูล", abbreviation: "สต.", englishName: "Satun" },
  {
    id: 11,
    name: "สมุทรปราการ",
    abbreviation: "สม.",
    englishName: "Samut Prakan",
  },
  {
    id: 75,
    name: "สมุทรสงคราม",
    abbreviation: "สส.",
    englishName: "Samut Songkhram",
  },
  {
    id: 74,
    name: "สมุทรสาคร",
    abbreviation: "สค.",
    englishName: "Samut Sakhon",
  },
  { id: 27, name: "สระแก้ว", abbreviation: "สก.", englishName: "Sa Kaeo" },
  { id: 19, name: "สระบุรี", abbreviation: "สบ.", englishName: "Saraburi" },
  { id: 17, name: "สิงห์บุรี", abbreviation: "สบ.", englishName: "Sing Buri" },
  { id: 64, name: "สุโขทัย", abbreviation: "สท.", englishName: "Sukhothai" },
  {
    id: 72,
    name: "สุพรรณบุรี",
    abbreviation: "สพ.",
    englishName: "Suphan Buri",
  },
  {
    id: 84,
    name: "สุราษฎร์ธานี",
    abbreviation: "สฎ.",
    englishName: "Surat Thani",
  },
  { id: 32, name: "สุรินทร์", abbreviation: "สร.", englishName: "Surin" },
  { id: 43, name: "หนองคาย", abbreviation: "นค.", englishName: "Nong Khai" },
  {
    id: 39,
    name: "หนองบัวลำภู",
    abbreviation: "นภ.",
    englishName: "Nong Bua Lamphu",
  },
  { id: 15, name: "อ่างทอง", abbreviation: "อท.", englishName: "Ang Thong" },
  {
    id: 37,
    name: "อำนาจเจริญ",
    abbreviation: "อจ.",
    englishName: "Amnat Charoen",
  },
  { id: 41, name: "อุดรธานี", abbreviation: "อด.", englishName: "Udon Thani" },
  { id: 53, name: "อุตรดิตถ์", abbreviation: "อต.", englishName: "Uttaradit" },
  {
    id: 61,
    name: "อุทัยธานี",
    abbreviation: "อท.",
    englishName: "Uthai Thani",
  },
  {
    id: 34,
    name: "อุบลราชธานี",
    abbreviation: "อบ.",
    englishName: "Ubon Ratchathani",
  },
  { id: 98, name: "เบตง", abbreviation: "", englishName: "Betong" },
];
